#!/bin/bash

ARGUMENTS="$@"
CWD=$(pwd)
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIRNAME="$(dirname "$(readlink -f "$0")")"

# with help from https://stackoverflow.com/a/29754866,

# saner programming env: these switches turn some bugs into errors
set -o errexit -o pipefail -o noclobber -o nounset

! getopt --test > /dev/null 
if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    echo "Sorry, `getopt --test` failed in this environment."
    exit 1
fi

OPTIONS=hdi:o:n:
LONGOPTS=help,docker,input:,output:,name:

# -use ! and PIPESTATUS to get exit code with errexit set
# -temporarily store output to be able to check for errors
# -activate quoting/enhanced mode (e.g. by writing out “--options”)
# -pass arguments only via   -- "$@"   to separate them correctly
! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
    # e.g. return value is 1
    #  then getopt has complained about wrong arguments to stdout
    exit 2
fi
# read getopt’s output this way to handle the quoting right:
eval set -- "$PARSED"

HELP=n DOCKER=n
INPUT=- OUTPUT=- NAME=-
while true; do
    case "$1" in
        -h|--help)
            HELP=y
            shift
            ;;
        -d|--docker)
            DOCKER=y
            shift
            ;;
        -i|--input)
            INPUT="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT="$2"
            shift 2
            ;;
        -n|--name)
            NAME="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error"
            exit 3
            ;;
    esac
done

if
  [ "${HELP}" == "y" ] || \
  [ "${INPUT}" == "-" ] || \
  [ "${OUTPUT}" == "-" ]
then
  cat >&2 <<EOF
Usage:
  debian-image-builder [options]

  Arguments:

    --input <path>: required directory of input image spec
    --output <path>: required directory to output build results
    --name <name>: optional name of image

  Flags:

    -h, --help: show this usage
    -d, --docker: build image using docker

  Examples:

    debian-image-builder --docker --input ./examples/simple --output ./output
EOF
  exit 1
fi

if [ "${NAME}" == "-" ]
then
  NAME="$(basename "${INPUT}")"
fi

# echo ARGUMENTS: $ARGUMENTS
# echo CWD: $CWD
# echo DIRNAME ${DIRNAME}
# echo PATH: $PATH

# echo DOCKER: $DOCKER
# echo HELP: $HELP
# echo INPUT: $INPUT
# echo OUTPUT: $OUTPUT
# echo NAME ${NAME}

if [ "${DOCKER}" = "y" ]
then
  ${DIRNAME}/build-docker ${ARGUMENTS}
else
  umask 022
  mkdir -p "${CWD}/${OUTPUT}"
  cd "${CWD}/${INPUT}"
  ls /app/vmdb2
  env -i LC_CTYPE=C.UTF-8 PATH="/usr/sbin:/sbin:$PATH" \
    vmdb2 \
      --rootfs-tarball "${CWD}/${OUTPUT}/${NAME}.tar.gz" \
      --output "$CWD/$OUTPUT/$NAME.img" \
      --log "$CWD/$OUTPUT/$NAME.log" \
      "${CWD}/${INPUT}/spec.yml" &
  build_pid=$!
  sleep 1
  tail -f -n +0 --pid=$build_pid $CWD/$OUTPUT/$NAME.log
  cd "${CWD}"
fi
